### ISSUE TITLE
BuildCraft and IC2 interaction issue

### ISSUE THREAD

**Issue by MoraglarKhilen** [AlmuraDev/GameServer#10]
The IC2 SemiFluid Generator (SFG) used to accept BC Oil and (refining Oil) Fuel. With the newest BC rev. Oil is now refined into multiple types and only Oil(Cool) is still recognizable to the IC2 SFG as Oil but no other I have tried will load into the SFG ( I have tried Mixed Light Fuels(cool), Dense Fuel(Cool), and Fuel(Cool).)

**Comment by TherayTharow** [comment]
This can be fixed i think be adding a custom recipes for it

**Comment by Dockter** [comment]
This has to go back to either IC2 or Buildcraft.  Almura can't touch this.
