### ISSUE TITLE
Railcraft Railroad in Public Domain

### ISSUE THREAD

**Issue by liach** [AlmuraDev/GameServer#11]
See AlmuraDev/Almura#295

**Comment by liach** [comment]
By the way, this time railways will be in orilla instead because of all the history.

**Comment by Dockter** [comment]
I support this.  Let me know when you want to start.

**Comment by liach** [comment]
I will do some work on railcraft's side before beginning this. currently, i need to enhance server control for minecart placements and signals, etc.
