### ISSUE TITLE
slime island blue slime spawn rate

### ISSUE THREAD

**Issue by TherayTharow** [AlmuraDev/GameServer#12]
The blue slime will spawn jump off the island make smaller ones, and hundreds of them will spawn
This lag the server heavily doc had to restart the server.
the solution is to slow down the spawn rate to one a time not 15 at a time

ceredwin

**Comment by Dockter** [comment]
Haven't figured out how to slow spawn rate as of yet.

**Comment by TherayTharow** [comment]
is there a way to stop them for spawning until b50 update

**Comment by TherayTharow** [comment]
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/modification-development/1436796-how-do-you-change-spawn-rates

does that work

**Comment by Dockter** [comment]
We use a mod called CustomMobSpawner due to MoCreatures.  Any idea what I would need to set?

**Comment by TherayTharow** [comment]
\AppData\Roaming\.technic\modpacks\almura-3\config\CustomSpawner\overworld
or some thing else in the customspawner config

**Comment by Dockter** [comment]
I've got nothing for this yet.
