### ISSUE TITLE
Trees Will Not Generate Because of file not set

### ISSUE THREAD

**Issue by TherayTharow** [AlmuraDev/GameServer#14]
Someone Can`t  Spell The Word Birch
![screenshot 1](https://user-images.githubusercontent.com/39970604/42403885-3b683364-814a-11e8-8c5e-c8615e877339.png)
![screenshot 4](https://user-images.githubusercontent.com/39970604/42403886-3b7bc262-814a-11e8-9aef-83022bca621e.png)
And No Max
![screenshot 3](https://user-images.githubusercontent.com/39970604/42403891-5097afa8-814a-11e8-8f35-ffd797d8b102.png)
![screenshot 2](https://user-images.githubusercontent.com/39970604/42403892-50ada740-814a-11e8-9805-23b653e8255d.png)

**Comment by Dockter** [comment]
This is a valid point.  Will investigate.

**Comment by Dockter** [comment]
I fixed Liku, they will only generate in birch_forest.

**Comment by Dockter** [comment]
Fixed Light Ephedra as well.

**Comment by TherayTharow** [comment]
please fix of client side one as well

**Comment by liach** [comment]
@PowellA12 That should be fixed once a new version on technic is pushed

**Comment by TherayTharow** [comment]
\TConstruct-1.12.2-2.10.1.87\slimeknights\tconstruct\world\worldgen you can add your tree to the island
gen file

**Comment by Dockter** [comment]
Doesn't work like that.
