### ISSUE TITLE
can`t make marble tile because the recipe is not right. 

### ISSUE THREAD

**Issue by TherayTharow** [AlmuraDev/GameServer#15]
"almura:horizontal/building/marbleblock" needs to be "almura:normal/building/marbleblock" to work
![screenshot 5](https://user-images.githubusercontent.com/39970604/42407388-21168902-8181-11e8-8366-e7aef937a8ea.png)

**Comment by TherayTharow** [comment]
also you can do this with some other furnace recipes

**Comment by Dockter** [comment]
Fixed in dev.  Will roll a new content build this evening to the dev server.
