### ISSUE TITLE
List of Things not set and how to fix them I think with the custom Almura Blocks 

### ISSUE THREAD

**Issue by TherayTharow** [AlmuraDev/GameServer#18]
Lets Take a File C:\YouDon`tGetToKnow\almura-3-client-resources-1.12.2-b49d\assets\fs\assets\almura\content\block\horizontal\building
`{
    "material": "minecraft:ground",  < This Needs to be The Correct Material 
    "map_color": "minecraft:dirt", < This I think need to be the same as material most of the time
    "item_group": "almura:building",   
    "state": {                                            < why don`t most of the blocks have this
        "facing=east": {                                  The orientation of the block
            "parent": "facing=north"               
        },
        "facing=south": {
            "parent": "facing=north"
        },
        "facing=north": {
            "hardness": 1.5,
            "resistance": 10.0,
            "action": {
                "destroy": [
                    {
                        "drop": [
                            {
                                "item": "almura:horizontal/building/brownmarbletile",
                                "amount": 1
                            }
                        ]
                    }
                ]
            }
        },
        "facing=west": {
            "parent": "facing=north"
        }
    }
}                                                         
`

**Comment by Dockter** [comment]
What are you pointing out as the issue?

**Comment by liach** [comment]
is it that marble should not be like dirt?

**Comment by Dockter** [comment]
related to maps?

**Comment by TherayTharow** [comment]
the Block should be rock so it is mined with a pickaxe  in stead of a shovel
also not all blocks can be rotated when they should be.

**Comment by TherayTharow** [comment]
yes and yes

**Comment by TherayTharow** [comment]
but the map i have no idea how to deal with

**Comment by Dockter** [comment]
@kashike does that material classification determine which tool enum to use?

**Comment by TherayTharow** [comment]
Yes

**Comment by TherayTharow** [comment]
From my testing

**Comment by liach** [comment]
@dockter well even if you mine with wrong tools the block drops.

**Comment by TherayTharow** [comment]
Yes but silktouch does not work
Also the incorrect tool brakes the tool more then using the right one and it is way slower

**Comment by Dockter** [comment]
Silk Touch isnt implemented yet.  Its on our todo list.
