### ISSUE TITLE
Sorry the redstone problem is not because of sponge

### ISSUE THREAD

**Issue by TherayTharow** [AlmuraDev/GameServer#20]
https://github.com/SpongePowered/SpongeCommon/issues/2003#
and did some more testing and sponge is not the problem the almura.jar is 
no other mod but sponge forge almura.jar and malisiscore

**Comment by TherayTharow** [comment]
After more testing it is the almura jar at first i thought it was sponge thinking that it was the only thing that would have the hooks in minecraft to do that

**Comment by Zidane** [comment]
It can't be the Almura jar. We don't touch redstone...

**Comment by TherayTharow** [comment]
sponge with no mods does not do that

**Comment by TherayTharow** [comment]
![with out 2](https://user-images.githubusercontent.com/39970604/43017842-3dc9196a-8c1d-11e8-95e3-7d744d02917f.png)
![with out 1](https://user-images.githubusercontent.com/39970604/43017843-3dd71650-8c1d-11e8-9177-4dfa92bf799c.png)

with 
![with almura jar 2](https://user-images.githubusercontent.com/39970604/43017866-5049f2f8-8c1d-11e8-9900-24e545811229.png)
![with almura jar 1](https://user-images.githubusercontent.com/39970604/43017867-506474fc-8c1d-11e8-91ec-756af1d03d76.png)

**Comment by TherayTharow** [comment]
and this is in the Technic one
no other mod except the almura.jar dependencies

**Comment by Dockter** [comment]
@Grinch @gabizou how is that possible?

**Comment by Zidane** [comment]
@Dockter What SpongeForge does the latest version of Almura in the TechnicPack roll out?

**Comment by Dockter** [comment]
The server and the client are mismatched at the moment.  The Client is running a SF build from 7/3 on this commit: https://github.com/SpongePowered/SpongeForge/commit/8e32ba49050a4c75bfba47768940f9276e3b90ab, the server is running 3304

Im 95% sure of the above.

**Comment by PowellA12** [comment]
spongeforge-1.12.2-2705-7.1.0-BETA-0

**Comment by Dockter** [comment]
@kashike could something with the content loader explain this?  User claims if they remove JUST Almura from the mod pack then this functions like Vanilla.

**Comment by TherayTharow** [comment]
I Think I know why is is happening it because of the buckect stacking minecraft is looking  of a full stack
of buckects a stack of waters buckects is nornally only 1 so it out puts a redstone of 2, when the buckect is emtey it is not a full stack so minecraft only outputs as 1 hopefully this makes sense

**Comment by TherayTharow** [comment]
and the fix i have no idea on
