### ISSUE TITLE
List of things that have Issues that i found

### ISSUE THREAD

**Issue by TherayTharow** [AlmuraDev/GameServer#21]
you can set fire to res by blaze through stargate,
you can farm blocks from castle using ic2 mining lazzer, Dynamite 
Dynamite will break a stargate when the stargate is open,
Dynamite will sometimes set fire to that area
too meny block in a shulker box put in a backpack will give you nbt error

**Comment by TherayTharow** [comment]
slime block machines can work in res in out of them

**Comment by TherayTharow** [comment]
item frames can be fully used

**Comment by TherayTharow** [comment]
something from 2.5 is the forcefield at the castle and be toggled

**Comment by TherayTharow** [comment]
Pressing revive does not work and trys to open the exchange. ??
this does not make sense

**Comment by Dockter** [comment]
How exactly can you start a fire through the stargate?

**Comment by TherayTharow** [comment]
have it follow you through stargate or spawner with some water in to stargate
