### ISSUE TITLE
No way to create Marble Tile.

### ISSUE THREAD

**Issue by ghost** [AlmuraDev/GameServer#22]
You cannot smelt marble in a furnace and obtain marble tile. [https://imgur.com/6mBeeJ7](https://imgur.com/6mBeeJ7)

**Comment by TherayTharow** [comment]
no just unclose this one https://github.com/AlmuraDev/GameServer/issues/15

**Comment by Dockter** [comment]
Fixed in 1.12.2-b50-r2.
