### ISSUE TITLE
Rendering Issue with Almura Player List HUD.

### ISSUE THREAD

**Issue by ghost** [AlmuraDev/GameServer#23]
[Almura](https://imgur.com/a/bRkf61b) Clouds are 2D, nothing can be seen above them when playerList HUD isnt present.

[Vanilla](https://imgur.com/a/FGkSwWx)

**Comment by TherayTharow** [comment]
sorry  that is some thing to do with the hight limt because going a bove a hight it will fix

**Comment by ghost** [comment]
What.

**Comment by TherayTharow** [comment]
go above a height and the problem will go a way

**Comment by Dockter** [comment]
I can't reproduce this.
