### ISSUE TITLE
Book Item in Dirt Chest is Infinite

### ISSUE THREAD

**Issue by TherayTharow** [AlmuraDev/GameServer#24]
The Dirt chest comes with a book braking the chest after removing the book then puting back down 
the dirt chest will still have a book in it and this can be done for ever

**Comment by TherayTharow** [comment]
![2018-07-23_01 09 06](https://user-images.githubusercontent.com/39970604/43058346-325aa072-8e15-11e8-9c89-2f944d45032e.png)
![2018-07-23_01 07 41](https://user-images.githubusercontent.com/39970604/43058347-326968be-8e15-11e8-9212-25267b13f11f.png)
![2018-07-23_01 08 19](https://user-images.githubusercontent.com/39970604/43058348-32781742-8e15-11e8-8dca-ba4b2694eccf.png)
![2018-07-23_01 08 25](https://user-images.githubusercontent.com/39970604/43058349-3284dd42-8e15-11e8-9bc9-5d8757342c2e.png)
![2018-07-23_01 08 34](https://user-images.githubusercontent.com/39970604/43058350-32927024-8e15-11e8-9ef7-bcf850251cb4.png)

**Comment by liach** [comment]
This should be a bug of ironchest mod

**Comment by TherayTharow** [comment]
yep but put it here so people know not to do

**Comment by Dockter** [comment]
I cannot solve this within Almura.
