### ISSUE TITLE
salt ore makes 8 and not 9?? when takes 9 to make

### ISSUE THREAD

**Issue by TherayTharow** [AlmuraDev/GameServer#26]
![2018-07-29_00 38 14](https://user-images.githubusercontent.com/39970604/43363011-d03e96d4-92c7-11e8-928c-b379bed9ab37.png)
![2018-07-29_00 38 18](https://user-images.githubusercontent.com/39970604/43363012-d04dd982-92c7-11e8-94f0-0caa2759e203.png)

**Comment by Dockter** [comment]
This was fixed a while ago.
