### ISSUE TITLE
Claim vs. Explosives

### ISSUE THREAD

**Issue by Dieheart3** [AlmuraDev/GameServer#29]
Welp, TnT won't destroy blocks inside a claim but Tinkers' throwable explosives (EFLNs) will... they despawn if thrown inside the claim but can do some real damage if thrown just outside the claim edge. Now this in in the right place..

**Comment by PowellA12** [comment]
I'am nice enough to at lest to this kind of testing on the dev server

**Comment by Dockter** [comment]
Can't do anything about them destroying stuff on the border.
