### ISSUE TITLE
Dying Iron Backpacks

### ISSUE THREAD

**Issue by Dieheart3** [AlmuraDev/GameServer#30]
The iron backpack dye recipes for both normal and iron backpacks use a bit of code that only works in singleplayer now... This leads to a dupe bug. If you put the backpack and dye in a crafting bench, click the output even though there is nothing there, then the dye or backpack whichever you remove first gets duplicated... This includes the contents of the backpack if you take the it out first. Need to remove the dye recipes or fix the code. This is a known issue on the iron backpacks site as well.

**Comment by TherayTharow** [comment]
This sounds nice for duping zpm's
Not that i would ever do that.
i Don't have any to do it with

**Comment by Dockter** [comment]
Cannot reproduce this.  Perhaps SpongeForge is blocking this now, I don't know.
