### ISSUE TITLE
Employments in cities

### ISSUE THREAD

**Issue by liach** [AlmuraDev/GameServer#31]
Since the introduction of skills system, it becomes fairly hard for new players to survive in the wild in dakara in the first few nights. If the server introduces employments and apprenticeships in cities in asgard or orilla, these new players may have a way to level up their skills without taking risk of having no food or cannot build shelter. Of course, the apprenticeship will end probably around the iron armor level, I assume, so that people should move on on their own for higher levels.

**Comment by Dockter** [comment]
This is already a planned feature.  Though I want to make it clear, new players can now use iron swords and craft them.
