### ISSUE TITLE
buildcraft and ic2 power cart cause the game to crash 

### ISSUE THREAD

**Issue by TherayTharow** [AlmuraDev/GameServer#32]

**Comment by TherayTharow** [comment]
i'am work on getting the log

**Comment by TherayTharow** [comment]
https://gist.github.com/PowellA12/fc519897feec016c1b0b4fc8a3155bb8
and the save will crash right after it loads

**Comment by liach** [comment]
This is not ic2 or buildcraft. This is caused by customspawner mod.

**Comment by TherayTharow** [comment]
k all i did was connect four zpms to together with a gold pipe in the center of them so all four where on the same one block of pipe
