### ISSUE TITLE
Subversion of leveling system

### ISSUE THREAD

**Issue by ghost** [AlmuraDev/GameServer#33]
In order to access the IC2 CESU, a crafting level of 50 is required. This can be subverted by placing a tinkers construct workbench adjacent to the CESU. placing an item in the workbench's slot for the CESU will charge said item. Glitch most likely works with other methods of energy storage(MFSU, MFE, BatBox).

**Comment by Dockter** [comment]
Fixed in b65.  Now all TConstruct blocks are locked out until crafting lvl 55.
