### ISSUE TITLE
Crafting skill EXP not issued when using Tinker's Construct workbench. [And other bugs]

### ISSUE THREAD

**Issue by ghost** [AlmuraDev/GameServer#34]

**Comment by ghost** [comment]
Mining mossy cobblestone does not contribute EXP to mining skill.

**Comment by ghost** [comment]
Crafting signs does not contribute crafting skill EXP.

**Comment by ghost** [comment]
Crafting furnaces does not contribute to crafting skill EXP.

**Comment by ghost** [comment]
Crafting pressure plates and buttons also does not contribute crafting skill EXP.

**Comment by ghost** [comment]
Spruce doors & Iron blocks don't contribute crafting skill EXP.

**Comment by Dockter** [comment]
TConstruct workbench never will contribute XP because TC doesn't use events like the rest of the damn community...

**Comment by Dockter** [comment]
Added doors, signs, furnaces, work bench and added 3 variants of stone brick.  Leaving buttons and plates out of this for now.
