### ISSUE TITLE
[Request] Dropped saplings plant themselves

### ISSUE THREAD

**Issue by ghost** [AlmuraDev/GameServer#35]

**Comment by liach** [comment]
please don't.

**Comment by ghost** [comment]
Why not?

**Comment by liach** [comment]
That would cause lags and causes major troubles when players try to clean forests.

**Comment by ghost** [comment]
Fair enough.

**Comment by TherayTharow** [comment]
Also trying to clear a area premimtly would be much harder.

**Comment by Dockter** [comment]
I will try to be a clear as I can on this....

There isn't a snow balls chance in hell of this happening.

**Comment by TherayTharow** [comment]
sorry reading my email back log from github did not see that it got closed
