### ISSUE TITLE
Infinite Arrow Glitch

### ISSUE THREAD

**Issue by ghost** [AlmuraDev/GameServer#36]
Using an obsidian transport pipe with a gold transport pipe, you can shoot an infinite use Tinker's shuriken and get Minecraft arrows.

https://gyazo.com/a6603fd00fe47b7af965c9e8491ab595

**Comment by liach** [comment]
should be a ticon bug.

**Comment by Dockter** [comment]
This bug needs to be reported to TinkersConstruct.
