### ISSUE TITLE
Some Almura Custom Blocks Missing After B64

### ISSUE THREAD

**Issue by dubbeanh** [AlmuraDev/GameServer#37]
In B63, my floor was made of "Advanced Stone Brick".

After updating to B64, all the Almura blocks are gone.

**Comment by Dockter** [comment]
This was an intended change.  Get with an admin and I will compensate you with blocks and funding to fix the issue.  This was caused by a flaw in how I implemented the blocks many months ago.

**Comment by dubbeanh** [comment]
I appreciate the offer. Its just some stone, and nothing worth the fuss. I was just reporting the issue to make sure it was known. Thanks.
