### ISSUE TITLE
SGCraft: DHD Sounds Don't Obey Config File Sound Setting

### ISSUE THREAD

**Issue by dubbeanh** [AlmuraDev/GameServer#38]
In the config file, last section, I set the following option:
   D:soundVolume=0.4

This has led to a drastic volume reduction (as intended) for stargate operations. It however does not affect the dialing sounds from the DHD.

Intended?

**Comment by Dockter** [comment]
Will investigate.  This ticket needs to go onto the SGCraft repo not "GameServer"

**Comment by dubbeanh** [comment]
Moved to SGCraft repo.

https://github.com/AlmuraDev/SGCraft/issues/48

**Comment by Dockter** [comment]
Fixed in > 2.0.0 - alpha 2
