### ISSUE TITLE
Intermittent Client Crashes involving Dirt Stairs

### ISSUE THREAD

**Issue by dubbeanh** [AlmuraDev/GameServer#39]
It isn't an every time thing, but since I started putting down dirt stairs or breaking dirt stairs, I've had a few crashes. Haven't had any crash issues before the dirt stairs. The following is a copy of the report. I will remove the stairs when I get back in and report back any additional crashes.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.0-SNAPSHOT.jar)
  AlmuraLoadingPlugin (almura-mc[1.12.2]-forge[2768]-sf[RC3497]-b64.jar)
  SpongeCoremod (spongeforge-1.12.2-2768-7.1.6-RC3594.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 2/21/19 2:42 PM
Description: Unexpected error

java.lang.NullPointerException: CatalogDelegate{type=interface org.spongepowered.api.item.ItemType, id=minecraft:gold_shovel}
	at java.util.Objects.requireNonNull(Unknown Source)
	at com.almuradev.content.component.delegate.Delegate.require(Delegate.java:37)
	at com.almuradev.content.component.delegate.DelegateCollection$1.computeNext(DelegateCollection.java:33)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at java.util.AbstractCollection.contains(Unknown Source)
	at com.almuradev.content.type.block.type.stair.StairBlockImpl.effectiveTool(StairBlockImpl.java:642)
	at net.minecraft.item.ItemTool.redirect$effectiveOn$zbi000(ItemTool.java:532)
	at net.minecraft.item.ItemTool.func_150893_a(ItemTool.java:62)
	at net.minecraft.item.ItemPickaxe.func_150893_a(SourceFile:89)
	at net.minecraft.item.ItemStack.func_150997_a(ItemStack.java:212)
	at net.minecraft.entity.player.InventoryPlayer.func_184438_a(InventoryPlayer.java:585)
	at net.minecraft.entity.player.EntityPlayer.getDigSpeed(EntityPlayer.java:785)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:258)
	at net.minecraft.block.Block.func_180647_a(Block.java:559)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:412)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:246)
	at net.optifine.override.PlayerControllerOF.func_180511_b(PlayerControllerOF.java:49)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.redirect$onClickMouse$bck000(Minecraft.java:3477)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2249)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Objects.requireNonNull(Unknown Source)
	at com.almuradev.content.component.delegate.Delegate.require(Delegate.java:37)
	at com.almuradev.content.component.delegate.DelegateCollection$1.computeNext(DelegateCollection.java:33)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at java.util.AbstractCollection.contains(Unknown Source)
	at com.almuradev.content.type.block.type.stair.StairBlockImpl.effectiveTool(StairBlockImpl.java:642)
	at net.minecraft.item.ItemTool.redirect$effectiveOn$zbi000(ItemTool.java:532)
	at net.minecraft.item.ItemTool.func_150893_a(ItemTool.java:62)
	at net.minecraft.item.ItemPickaxe.func_150893_a(SourceFile:89)
	at net.minecraft.item.ItemStack.func_150997_a(ItemStack.java:212)
	at net.minecraft.entity.player.InventoryPlayer.func_184438_a(InventoryPlayer.java:585)
	at net.minecraft.entity.player.EntityPlayer.getDigSpeed(EntityPlayer.java:785)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:258)
	at net.minecraft.block.Block.func_180647_a(Block.java:559)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:412)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:246)
	at net.optifine.override.PlayerControllerOF.func_180511_b(PlayerControllerOF.java:49)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.redirect$onClickMouse$bck000(Minecraft.java:3477)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2249)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['pdubs'/655034, l='MpServer', x=-4986.45, y=39.00, z=-2937.90]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-141,80,305), Chunk: (at 3,5,1 in -9,19; contains blocks -144,0,304 to -129,255,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 669863289 game time, 609267075 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 106 total; [EntityGuardian['Guardian'/656396, l='MpServer', x=-5020.82, y=40.35, z=-2948.69], EntityMooshroom['§fMooshroom'/655105, l='MpServer', x=-5063.57, y=70.00, z=-2952.54], EntityGuardian['Guardian'/656129, l='MpServer', x=-4980.34, y=35.13, z=-2941.71], EntityMooshroom['§fMooshroom'/655106, l='MpServer', x=-5062.55, y=67.00, z=-2953.64], EntityPlayerSP['pdubs'/655034, l='MpServer', x=-4986.45, y=39.00, z=-2937.90], EntityGuardian['Guardian'/655123, l='MpServer', x=-5026.63, y=35.00, z=-2944.58], EntityChicken['§fChicken'/655125, l='MpServer', x=-5055.20, y=66.00, z=-2937.66], EntityGuardian['Guardian'/655124, l='MpServer', x=-5029.88, y=45.00, z=-2957.67], EntityMooshroom['§fMooshroom'/655126, l='MpServer', x=-5048.53, y=68.00, z=-2931.19], EntityGuardian['Guardian'/656405, l='MpServer', x=-5029.70, y=32.76, z=-2937.86], EntityGuardian['Guardian'/655913, l='MpServer', x=-4970.64, y=30.00, z=-2956.09], EntityMooshroom['§fMooshroom'/655139, l='MpServer', x=-5045.21, y=63.00, z=-2949.45], EntityMooshroom['§fMooshroom'/655138, l='MpServer', x=-5046.55, y=63.00, z=-2949.45], EntityChicken['§fChicken'/655141, l='MpServer', x=-5056.27, y=66.00, z=-2938.80], EntityGuardian['Guardian'/656166, l='MpServer', x=-4941.12, y=47.24, z=-2958.74], EntityMooshroom['§fMooshroom'/655140, l='MpServer', x=-5046.04, y=63.00, z=-2950.70], EntityGuardian['Guardian'/656679, l='MpServer', x=-4984.67, y=44.99, z=-2975.03], EntityChicken['§fChicken'/655143, l='MpServer', x=-5056.34, y=66.00, z=-2938.09], EntityMooshroom['§fMooshroom'/655142, l='MpServer', x=-5058.78, y=67.00, z=-2934.37], EntityGuardian['Guardian'/655161, l='MpServer', x=-5026.48, y=32.00, z=-2943.58], EntityGuardian['Guardian'/655418, l='MpServer', x=-4965.32, y=31.00, z=-2973.96], EntityGuardian['Guardian'/656698, l='MpServer', x=-4942.16, y=44.94, z=-2924.47], EntityGuardian['Guardian'/655163, l='MpServer', x=-5028.51, y=32.00, z=-2938.87], EntityGuardian['Guardian'/655162, l='MpServer', x=-5025.51, y=32.00, z=-2942.46], MoCEntityManderin['Manderin'/655164, l='MpServer', x=-5055.53, y=62.00, z=-2917.75], EntityBoat['Boat'/655167, l='MpServer', x=-5058.10, y=62.52, z=-2892.66], EntityBat['Bat'/655166, l='MpServer', x=-5041.57, y=16.72, z=-2873.05], EntityGuardian['Guardian'/655922, l='MpServer', x=-5023.15, y=39.49, z=-2925.79], EntityGuardian['Guardian'/655152, l='MpServer', x=-5022.44, y=33.00, z=-2947.87], EntityGuardian['Guardian'/655923, l='MpServer', x=-4986.74, y=31.00, z=-2984.98], EntityGuardian['Guardian'/655668, l='MpServer', x=-5003.37, y=31.00, z=-2903.72], EntityGuardian['Guardian'/655158, l='MpServer', x=-5025.04, y=32.00, z=-2941.45], EntityGuardian['Guardian'/655689, l='MpServer', x=-4984.49, y=31.00, z=-2979.83], MoCEntityAngelFish['AngelFish'/655178, l='MpServer', x=-5013.66, y=61.47, z=-2859.58], EntityGuardian['Guardian'/655183, l='MpServer', x=-4994.55, y=31.00, z=-2895.50], EntityGuardian['Guardian'/655182, l='MpServer', x=-5001.41, y=31.00, z=-2891.27], MoCEntityAngelFish['AngelFish'/655171, l='MpServer', x=-5049.76, y=61.38, z=-2867.53], MoCEntityAngler['Angler'/655170, l='MpServer', x=-5040.94, y=60.92, z=-2873.10], EntityBat['Bat'/656710, l='MpServer', x=-4935.55, y=27.58, z=-2940.38], MoCEntityAnchovy['Anchovy'/655175, l='MpServer', x=-4995.80, y=61.54, z=-2878.69], EntityGuardian['Guardian'/656708, l='MpServer', x=-5006.00, y=45.00, z=-2916.08], MoCEntityHippoTang['HippoTang'/655195, l='MpServer', x=-5031.31, y=61.78, z=-3014.39], MoCEntityHippoTang['HippoTang'/655194, l='MpServer', x=-5030.78, y=62.40, z=-3009.04], EntityGuardian['Guardian'/656734, l='MpServer', x=-5000.45, y=50.51, z=-2919.19], EntityGuardian['Guardian'/656464, l='MpServer', x=-4982.38, y=34.29, z=-2905.57], EntityGuardian['Guardian'/656468, l='MpServer', x=-4997.08, y=34.70, z=-2903.35], EntityGuardian['Guardian'/655209, l='MpServer', x=-4989.86, y=30.00, z=-2949.37], EntityGuardian['Guardian'/655208, l='MpServer', x=-4968.10, y=32.00, z=-2977.48], EntityGuardian['Guardian'/655211, l='MpServer', x=-5018.57, y=33.00, z=-2925.02], EntityGuardian['Guardian'/656232, l='MpServer', x=-5022.48, y=38.30, z=-2949.05], EntityGuardian['Guardian'/655213, l='MpServer', x=-5022.51, y=32.00, z=-2932.45], EntityGuardian['Guardian'/655726, l='MpServer', x=-4954.77, y=41.00, z=-2937.41], EntityGuardian['Guardian'/655212, l='MpServer', x=-5020.59, y=32.00, z=-2938.79], EntityGuardian['Guardian'/655215, l='MpServer', x=-5027.58, y=32.00, z=-2940.84], EntityGuardian['Guardian'/655214, l='MpServer', x=-5023.13, y=32.00, z=-2934.80], EntityBat['Bat'/656237, l='MpServer', x=-5010.66, y=26.06, z=-2990.66], EntityGuardian['Guardian'/656749, l='MpServer', x=-4964.20, y=61.25, z=-2938.03], EntityGuardian['Guardian'/655201, l='MpServer', x=-5000.57, y=38.00, z=-2976.20], MoCEntityHippoTang['HippoTang'/655203, l='MpServer', x=-4993.27, y=61.35, z=-2987.24], EntityGuardian['Guardian'/655202, l='MpServer', x=-4995.96, y=32.00, z=-2981.66], EntityGuardian['Guardian'/655205, l='MpServer', x=-5019.58, y=35.00, z=-2960.58], MoCEntityGoldFish['GoldFish'/655207, l='MpServer', x=-4977.16, y=62.14, z=-3016.10], EntityGuardian['Guardian'/655206, l='MpServer', x=-5022.08, y=39.00, z=-2961.70], EntityGuardian['Guardian'/655461, l='MpServer', x=-4941.92, y=35.97, z=-2932.58], EntityGuardian['Guardian'/655227, l='MpServer', x=-4999.88, y=31.00, z=-2900.49], EntityGuardian['Guardian'/655740, l='MpServer', x=-5025.89, y=32.00, z=-2933.36], EntityGuardian['Guardian'/655219, l='MpServer', x=-4985.68, y=31.00, z=-2988.77], EntityGuardian['Guardian'/655218, l='MpServer', x=-5030.15, y=35.00, z=-2926.34], EntityGuardian['Guardian'/655220, l='MpServer', x=-4985.90, y=32.00, z=-2977.42], EntityGuardian['Guardian'/655222, l='MpServer', x=-4989.19, y=31.00, z=-2990.97], EntityGuardian['Guardian'/655989, l='MpServer', x=-5019.99, y=37.00, z=-2961.12], EntityCartChest['Chest Cart'/656522, l='MpServer', x=-5076.50, y=18.06, z=-3086.50], EntityGuardian['Guardian'/655242, l='MpServer', x=-4943.60, y=30.00, z=-2928.15], EntityGuardian['Guardian'/656265, l='MpServer', x=-4964.81, y=32.00, z=-2979.61], EntityGuardian['Guardian'/655245, l='MpServer', x=-4974.41, y=30.00, z=-2897.16], EntityGuardian['Guardian'/655246, l='MpServer', x=-4963.87, y=29.00, z=-2895.25], EntityGuardian['Guardian'/656269, l='MpServer', x=-4958.81, y=31.00, z=-2975.14], EntityGuardian['Guardian'/655237, l='MpServer', x=-4939.98, y=40.00, z=-2954.39], EntityGuardian['Guardian'/655750, l='MpServer', x=-4973.94, y=31.00, z=-2978.86], EntityGuardian['Guardian'/656774, l='MpServer', x=-4996.89, y=61.17, z=-2935.09], EntityGuardian['Guardian'/655236, l='MpServer', x=-4943.66, y=31.00, z=-2959.39], MoCEntitySalmon['Salmon'/655238, l='MpServer', x=-4927.86, y=59.04, z=-2953.33], EntityBoat['Boat'/655257, l='MpServer', x=-4985.44, y=62.52, z=-2874.68], MoCEntityHippoTang['HippoTang'/655259, l='MpServer', x=-4942.63, y=60.82, z=-2887.57], EntityGuardian['Guardian'/656531, l='MpServer', x=-4990.54, y=37.47, z=-2972.12], EntityGuardian['Guardian'/655251, l='MpServer', x=-4981.36, y=32.00, z=-2898.40], EntityGuardian['Guardian'/655253, l='MpServer', x=-4984.36, y=31.00, z=-2899.86], EntityGuardian['Guardian'/656535, l='MpServer', x=-5022.63, y=34.05, z=-2916.71], MoCEntityAnchovy['Anchovy'/655255, l='MpServer', x=-4925.04, y=61.16, z=-2914.83], MoCEntitySalmon['Salmon'/655254, l='MpServer', x=-4920.19, y=60.77, z=-2915.04], EntityCartChest['Chest Cart'/655271, l='MpServer', x=-4884.50, y=22.06, z=-2927.50], EntityCartChest['Chest Cart'/655270, l='MpServer', x=-4862.50, y=28.06, z=-2946.89], EntityGuardian['Guardian'/656304, l='MpServer', x=-4971.54, y=30.00, z=-2904.14], EntityGuardian['Guardian'/656582, l='MpServer', x=-4965.14, y=51.08, z=-2902.78], EntityGuardian['Guardian'/656580, l='MpServer', x=-5009.53, y=42.00, z=-2907.60], EntityGuardian['Guardian'/656091, l='MpServer', x=-4974.50, y=31.00, z=-2920.37], EntityBat['Bat'/655068, l='MpServer', x=-5063.51, y=25.10, z=-2982.25], EntityGuardian['Guardian'/655314, l='MpServer', x=-5027.38, y=32.00, z=-2943.14], EntityGuardian['Guardian'/655825, l='MpServer', x=-5004.11, y=44.00, z=-2930.86], EntityGuardian['Guardian'/656598, l='MpServer', x=-4951.61, y=30.00, z=-2910.77], EntityGuardian['Guardian'/656084, l='MpServer', x=-5010.27, y=40.00, z=-2973.27], EntityGuardian['Guardian'/656615, l='MpServer', x=-4956.84, y=30.00, z=-2947.43], EntityGuardian['Guardian'/656123, l='MpServer', x=-4951.47, y=30.00, z=-2924.09], EntityGuardian['Guardian'/655870, l='MpServer', x=-4993.24, y=32.00, z=-2975.97], EntityBat['Bat'/656636, l='MpServer', x=-5064.30, y=24.58, z=-2989.56], EntityBat['Bat'/656125, l='MpServer', x=-5060.25, y=36.11, z=-2910.20]]
	Retry entities: 1 total; [EntityCartChest['Chest Cart'/656522, l='MpServer', x=-5076.50, y=18.06, z=-3086.50]]
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8329390616 bytes (7943 MB) / 10737418240 bytes (10240 MB) up to 10737418240 bytes (10240 MB)
	LiteLoader Brand: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - WorldEditCUI version 1.12.1_01
	LaunchWrapper: 31 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
          - Transformer: $wrapper.org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: com.almuradev.almura.asm.transformer.AlmuraAccessTransformer
          - Transformer: org.spongepowered.mod.asm.transformer.SpongeAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockSpecialTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PotionEffectTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: $wrapper.invtweaks.forge.asm.ContainerTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 5 total; -Xms10240m -Xmx10240m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2814 Optifine OptiFine_1.12.2_HD_U_E3 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                   | Source                                           | Signature                                |
	|:------ |:-------------------- |:------------------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2                    | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                  | 9.42                      | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                  | 8.0.99.99                 | modpack.jar                                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2814              | modpack.jar                                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | spongeapi            | 7.1.0-40492ed4            | spongeforge-1.12.2-2768-7.1.6-RC3594.jar         | None                                     |
	| LCHIJA | sponge               | 1.12.2-7.1.6-SNAPSHOT     | spongeforge-1.12.2-2768-7.1.6-RC3594.jar         | None                                     |
	| LCHIJA | spongeforge          | 1.12.2-2768-7.1.6-RC3594  | spongeforge-1.12.2-2768-7.1.6-RC3594.jar         | None                                     |
	| LCHIJA | nucleus              | 1.8.2-S7.1                | Nucleus-1.8.2-S7.1-MC1.12.2-plugin.jar           | None                                     |
	| LCHIJA | almura               | 1.12.2-b64                | almura-mc[1.12.2]-forge[2768]-sf[RC3497]-b64.jar | None                                     |
	| LCHIJA | nucleus-api          | 1.4.4-S7.0                | almura-mc[1.12.2]-forge[2768]-sf[RC3497]-b64.jar | None                                     |
	| LCHIJA | bibliocraft          | 2.4.5                     | BiblioCraft[v2.4.5][MC1.12.2].jar                | None                                     |
	| LCHIJA | buildcraftlib        | 7.99.22-pre3-ed00d297cd3b | buildcraft-7.99.22-pre3-ed00d297cd3b.jar         | None                                     |
	| LCHIJA | buildcraftcore       | 7.99.22-pre3-ed00d297cd3b | buildcraft-7.99.22-pre3-ed00d297cd3b.jar         | None                                     |
	| LCHIJA | buildcraftbuilders   | 7.99.22-pre3-ed00d297cd3b | buildcraft-7.99.22-pre3-ed00d297cd3b.jar         | None                                     |
	| LCHIJA | buildcraftenergy     | 7.99.22-pre3-ed00d297cd3b | buildcraft-7.99.22-pre3-ed00d297cd3b.jar         | None                                     |
	| LCHIJA | buildcraftfactory    | 7.99.22-pre3-ed00d297cd3b | buildcraft-7.99.22-pre3-ed00d297cd3b.jar         | None                                     |
	| LCHIJA | buildcraftrobotics   | 7.99.22-pre3-ed00d297cd3b | buildcraft-7.99.22-pre3-ed00d297cd3b.jar         | None                                     |
	| LCHIJA | buildcrafttransport  | 7.99.22-pre3-ed00d297cd3b | buildcraft-7.99.22-pre3-ed00d297cd3b.jar         | None                                     |
	| LCHIJA | buildcraftsilicon    | 7.99.22-pre3-ed00d297cd3b | buildcraft-7.99.22-pre3-ed00d297cd3b.jar         | None                                     |
	| LCHIJA | cfm                  | 6.2.0                     | cfm-6.2.0-mc1.12.2.jar                           | None                                     |
	| LCHIJA | codechickenlib       | 3.2.2.354                 | CodeChickenLib-1.12.2-3.2.2.354-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | cookingforblockheads | 6.4.69                    | CookingForBlockheads_1.12.2-6.4.69.jar           | None                                     |
	| LCHIJA | customspawner        | 3.11.4                    | CustomMobSpawner-3.11.4.jar                      | None                                     |
	| LCHIJA | customnpcs           | 1.12                      | CustomNPCs_1.12.2(30Jan19).jar                   | None                                     |
	| LCHIJA | mocreatures          | 12.0.5                    | DrZharks MoCreatures Mod-12.0.5-hotfix1.jar      | None                                     |
	| LCHIJA | ic2                  | 2.8.111-ex112             | industrialcraft-2-2.8.111-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | inventorytweaks      | 1.63+release.109.220f184  | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironbackpacks        | 1.12.2-3.0.9-CUSTOM       | IronBackpacks-1.12.2-3.0.9-CUSTOM.jar            | None                                     |
	| LCHIJA | ironchest            | 1.12.2-7.0.59.842         | ironchest-1.12.2-7.0.59.842.jar                  | None                                     |
	| LCHIJA | jei                  | 4.13.1.225                | jei_1.12.2-4.13.1.225.jar                        | None                                     |
	| LCHIJA | journeymap           | 1.12.2-5.5.3              | journeymap-1.12.2-5.5.3.jar                      | None                                     |
	| LCHIJA | malisiscore          | 1.12.2-6.5.0-SNAPSHOT     | malisiscore-1.12.2-6.5.0-SNAPSHOT.jar            | None                                     |
	| LCHIJA | malisisdoors         | 1.12.2-7.3.0              | malisisdoors-1.12.2-7.3.0.jar                    | None                                     |
	| LCHIJA | mantle               | 1.12-1.3.1.21             | Mantle-1.12-1.3.1.21.jar                         | None                                     |
	| LCHIJA | nei                  | 2.4.2                     | NotEnoughItems-1.12.2-2.4.2.240-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | paydirtwashplant     | 1.0                       | paydirt-washingplant-2.0.jar                     | None                                     |
	| LCHIJA | railcraft            | 12.0.0-beta-5             | railcraft-12.0.0-beta-5.jar                      | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | sgcraft              | 1.13.2                    | SGCraft-1.20.3.jar                               | None                                     |
	| LCHIJA | tconstruct           | 1.12.2-2.10.1.87          | TConstruct-1.12.2-2.10.1.87.jar                  | None                                     |
	| LCHIJA | worldedit            | 6.1.9-SNAPSHOT            | worldedit-forge-mc1.12.1-6.1.9-SNAPSHOT-dist.jar | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.0-SNAPSHOT.jar)
  
AlmuraLoadingPlugin (almura-mc[1.12.2]-forge[2768]-sf[RC3497]-b64.jar)
  
SpongeCoremod (spongeforge-1.12.2-2768-7.1.6-RC3594.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13547 Compatibility Profile Context 25.20.15017.1010' Renderer: 'Radeon RX 590 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2814
	LWJGL: 2.9.4
	OpenGL: Radeon RX 590 Series GL version 4.6.13547 Compatibility Profile Context 25.20.15017.1010, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,sponge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: Almura x128.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor

**Comment by Dockter** [comment]
Issue found and fixed.  Bugfix will deploy with build 65.
