### ISSUE TITLE
Chests are invisible when placed until they are opened the first time

### ISSUE THREAD

**Issue by dubbeanh** [AlmuraDev/GameServer#46]
Vanilla chests, Ironchests, and vanilla ender chests all appear invisible until they are opened for the first time. Afterwards they work as normal.

It is worth noting that they show up if anyone opens them, not just me. I place a chest, someone else opens, I can see it now.

![2019-03-19_13 44 52](https://user-images.githubusercontent.com/719561/54633139-8ec93900-4a4d-11e9-8983-0cf62d8786e2.png)

**Comment by dubbeanh** [comment]
resource pack does not affect this behavior.

**Comment by Dockter** [comment]
My initial response:   "wtf...."

**Comment by Aaron1011** [comment]
I've experienced this same issue before, without Almura

**Comment by Dockter** [comment]
Vanilla bug, I cannot resolve.
