### ISSUE TITLE
Sponge multi-world stuff doesn't play nicely with mo creatures wyvern lair.

### ISSUE THREAD

**Issue by dubbeanh** [AlmuraDev/GameServer#47]
Two problems here:

1: Skills do not register properly in the wyvern dimension. They are tracked seperately. What skills are gained in the wyvern dimension, stay in the wyvern dimension. They are back to normal once leaving the wyvern dimension.

2: Mob spawning is borked. CMS, maybe? Its supposed to be wyverns, not a madhouse of crazy fast all mo creatures spawns.

**Comment by Dockter** [comment]
1.  Skills isn't setup with that world thus is an expected behavior.

2. Mob spawning......  Anyone have a bottle of fireball???  Anyone?

**Comment by dubbeanh** [comment]
The wiki suggests (but doenst outright say) the only thing that's supposed to spawn there is wyverns. Its so fast and dense, that I'm sure im hitting a mob cap and denying spawns.

Also, the nether and the end are per-world, whereas the wyvern dimension is server wide. it would be interesting to see what happens if you build a nether portal in there. which nether would it connect to?

**Comment by Zidane** [comment]
Sponge doesn't touch the spawner in this case, not our issue.

**Comment by Dockter** [comment]
@Zidane right, this has nothing to do with Sponge and everything to do with CMS configuration.

**Comment by dubbeanh** [comment]
That's my ignorance of which does what, my bad.
That being said, it's still an unexpected behavior/issue on the almura server. I'm just reporting what I see.

Tested the nether portal thing. Regardless of what world you are in when you go to the wyvern lair, a nether portal will dump you into dakara's nether.

**Comment by Inscrutable** [comment]
I had to bash the CMS config with a virtual brick to force Wyverns (and only wyverns) to spawn in the Wyvern dimension in Block19. CMS seems to have a number of problems (MoC mob spawns seem to stall in overworld after a while, no Moc mobs spawn in other overworld dims except in ocean, some things spawn just below the soil and die).
