### ISSUE TITLE
Refactor Content Food Configuration

### ISSUE THREAD

**Issue by Zidane** [AlmuraDev/GameServer#5]
* Refocus on making Players WANT to cook our food
* Scale Vanilla food down to be comparable to Content equivalents.

**Comment by Zidane** [comment]
@Dockter 

The math used to apply the saturation was wrong pre this commit: https://github.com/AlmuraDev/Almura/commit/ecba0429f6af83721a07936de7536c218f7a5314 . The math now follows the same scaling that Vanilla does and gives off correct Vanilla values.

Unfortunately this means that the values in your config went from vastly underpowered to vastly OVERPOWERED.

For example, sunflower seeds apply saturation of 1. Vanilla apples apply saturation of 0.3f. 1 is insanely overpowered and gives you 20 saturation is one bite. Saturation SHOULD be 0.1-0.3f for sunflower seeds in config files.

This will mean reviewing the food and adjusting the saturation files accordingly.

**Comment by Dockter** [comment]
I have nerf'd vanilla food which satisfies this ticket.
