### ISSUE TITLE
Unridden minecarts and locomotives nearly stop

### ISSUE THREAD

**Issue by dubbeanh** [AlmuraDev/GameServer#51]
I don't know the exact distance, but I would guesstimate about 16-20 blocks away, minecarts (and railcraft locomotives) nearly stop. They proceed at a snail's pace until a player gets close enough, then the cart remembers its old velocity and continues on at that previous speed until the same 16-20 block distance from player.

**Comment by Dockter** [comment]
@liach any clues on this?

**Comment by dubbeanh** [comment]
Is there an algorithm that cuts down entity movement when players aren't in the immediate vicinity? I notice most entities exhibit a behavior not unlike this.

**Comment by liach** [comment]
entity activation.

**Comment by dubbeanh** [comment]
culprit?
