### ISSUE TITLE
Almura wood planks aren't real planks.

### ISSUE THREAD

**Issue by dubbeanh** [AlmuraDev/GameServer#52]
wood planks from almura woods don't register as valid plankWood.

**Comment by Dockter** [comment]
Why is this an issue?

**Comment by dubbeanh** [comment]
I haven't looked into it, but I'm guessing they weren't added to an oredict. They just don't seem to be a suitable material for anything that calls for any:plankWood

**Comment by liach** [comment]
it shall not be compatible with modded and vanilla recipes using wooden planks.
