### ISSUE TITLE
Problems with Cruets in recipes

### ISSUE THREAD

**Issue by MoraglarKhilen** [AlmuraDev/GameServer#54]
Recipes that involve Dough and Cheese return Cruets.

**Comment by Dockter** [comment]
Fixed for b73.

**Comment by MoraglarKhilen** [comment]
Actually...
"Milk Filled Cruets still has a quote
and they do not return cruet in at least 2 recipes Scrambled eggs and Cheese that I tested so far
and they did with cheese making before update (only one i am sure of)
