### ISSUE TITLE
Review Broken Recipes

### ISSUE THREAD

**Issue by Zidane** [AlmuraDev/GameServer#6]
We've got a variety of recipes that are currently reporting broken in our internal game pack delivered through the modpack.

**Comment by Dockter** [comment]
What is broken?

**Comment by liach** [comment]
grape seed (conflict with raisin), butter cooking afaik. more coming.

**Comment by Zidane** [comment]
@Dockter 

I was more speaking of the json files when booting up (unless you resolved those recently?).

**Comment by Dockter** [comment]
Recipes are conflicting because stairs haven't been implemented.

**Comment by MoraglarKhilen** [comment]
Wreath (MrCrayfish)  and Plantball (IC2) conflict. Both use oak leaves in a box
