### ISSUE TITLE
Almura Tree leaves

### ISSUE THREAD

**Issue by Wolfeyeamd0** [AlmuraDev/GameServer#61]
When Almura Trees spawn and the leaves touch the ground the 'gaps' in the leaves make it so you can see through the ground and you can see ravines/caves/dungeons/etc. around you.

Trying to attach a picture - hoping this works.  Note that it is only happening when the leaves spawn on the ground.

![Xrayleaves](https://user-images.githubusercontent.com/13933473/57170880-7a5eb700-6dd5-11e9-8c0b-5684565f5d8f.PNG)

**Comment by Dockter** [comment]
https://github.com/AlmuraDev/Almura/commit/77523ad56e817d4d479f9e04202b4c1cfbc91dd1

**Comment by Dockter** [comment]
Fixed btw....
