### ISSUE TITLE
Unable to chop the first block of a tree

### ISSUE THREAD

**Issue by iHaX-MrChrissern** [AlmuraDev/GameServer#62]
Chopping and everything seems fine untill the block is chopped down it dissapear but if I re-log the block is still there and you obtained nothing from the block leaving the world like this.
![2019-06-08_13 10 48](https://user-images.githubusercontent.com/22635465/59146631-f198f380-89f0-11e9-9e58-892ba0862eee.png)

**Comment by Dockter** [comment]
I assume this issue was already resolved; please re-open if it isn't.
