### ISSUE TITLE
/spawn command error

### ISSUE THREAD

**Issue by CrocodileLundy** [AlmuraDev/GameServer#63]
![Spawn_event_type](https://user-images.githubusercontent.com/13926800/63219799-51bdbb80-c13f-11e9-9e43-71db5d055f1c.png)
When trying to execute the /spawn command, the below error occurs after the 5 second warmup.
Unexpected error running this command: SPAWN_EVENT_TYPE

**Comment by Dockter** [comment]
Yep, already reported to Nucleus here:  https://github.com/NucleusPowered/Nucleus/issues/1402
