### ISSUE TITLE
A small compiled list of minor things i've found of late

### ISSUE THREAD

**Issue by TherayTharow** [AlmuraDev/GameServer#65]
the nickname gui i can't use but i can use the command for it.
 i have found is that is that even i can't go to forest river and there's no spawn point for Marion
almost all the spawn points are fucked in where they are(i'll make a list for you) and no map for keystone? 

fucked spawn points
Atlantis
Cemaria - just move a bit south until it's in the staragte's claim
zeal
forest river is like Cemaria
Faerun
Marion - based off of where the map claims the spawn point is.
Highgarden
keystone

**Comment by TherayTharow** [comment]
I can Edit Signs in A res i don't own
![2020-04-26_23 01 13](https://user-images.githubusercontent.com/39970604/80330127-58461c00-8812-11ea-8bde-1e24535ca70c.png)

**Comment by Dockter** [comment]
This is likely fixed within b100 with us moving from GriefPrevention to Grief Defender.

**Comment by Dockter** [comment]
I'll fix the spawn points when I push b100 live.
