### ISSUE TITLE
Glass Bottle Duplication

### ISSUE THREAD

**Issue by mgwerner** [AlmuraDev/GameServer#69]
When crafting Mixed Vegetable Juice, a glass bottle and tomato gives tomato juice, a glass bottle and carrot gives carrot juice.  Tomato juice and carrot juice crafted together make one Mixed Vegetable juice, and return two empty bottles.  When the Mixed Vegetable juice is consumed, it returns one empty bottle, so there is a net gain of one bottle per crafting chain.

**Comment by Dockter** [comment]
Well.... that's a hum dingier...
